SELECT * FROM EMP_LARGE;

SELECT COUNT(*) FROM EMP_LARGE;

SELECT * FROM DEPT_LARGE;

SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME='EMP_LARGE';

CREATE INDEX IDX_ENAME ON EMP_LARGE(ENAME);

explain plan for
SELECT * FROM EMP_LARGE WHERE ENAME='Employee 501';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
============================================

CREATE INDEX IDX_JOB ON EMP_LARGE(JOB);

EXPLAIN PLAN FOR
SELECT /*+ INDEX (EMP_LARGE IDX_JOB) */ * FROM EMP_LARGE WHERE JOB='MANAGER';

S